Chair election 2023 - affiliations designated voters
w3c-cg/solid pull request #1
Opened 2023-11-08 15:21 UTC by elf-pavlik

As discussed during https://github.com/solid/specification/pull/595

2023-11-08 15:23 UTC, michielbdejong approved these changes

2023-11-08 17:48 UTC, elf-pavlik commented
@csarven it might be helpful to include the list of organization directly in the email (easy copy & paste):

Adobe
Aggadom
Brickdoc
Defense Information Systems Agency
Digita
Electronics and Telecommunications Research Institute (ETRI)
Ghent University
Graphmetrix, Inc.
Inrupt Inc.
Institut National de Recherche en Informatique et en Automatique (Inria)
Janeiro Digital
Massachusetts Institute of Technology (MIT)
Muze
OpenLink Software Inc.
REDPENCIL
Sakak
Startin'blox
Universidad Politécnica de Madrid
W3C
WU (Wirschaftsuniversität Wien) - Vienna University of Economics and Business

2023-11-08 18:23 UTC, acoburn approved these changes

2023-11-08 23:36 UTC, csarven requested changes

2023-11-08 23:36 UTC, csarven commented on elections/2023/affiliation-designated-voters.md
> +Open for edits until 14-11-2023
```suggestion
Open for edits until 2023-11-14
```

2023-11-08 23:36 UTC, csarven commented on elections/2023/affiliation-designated-voters.md
> +To designate a representative please edit the table and add their name in the *Designated* column.
```suggestion
To designate a representative please edit the table and add their full name (as it appears in their W3C account or https://www.w3.org/groups/cg/solid/participants/ ) in the *Designated* column.
```

2023-11-08 23:36 UTC, csarven commented on elections/2023/affiliation-designated-voters.md
> +List generated on 08-11-2023 using [solid-ecosystem-monitor](https://github.com/VirginiaBalseiro/solid-ecosystem-monitor/pull/2)
```suggestion
List generated on 2023-11-08 using [solid-ecosystem-monitor](https://github.com/VirginiaBalseiro/solid-ecosystem-monitor/pull/2)
```

2023-11-09 18:43 UTC, VirginiaBalseiro approved these changes

2023-11-09 19:23 UTC, csarven commented on elections/2023/affiliation-designated-voters.md
> +* Aaron Coburn - self-designated [during Solid CG meeting 08-11-2023](https://github.com/solid/specification/pull/595)
```suggestion
* Aaron Coburn - self-designated [during Solid CG meeting 2023-11-08](https://github.com/solid/specification/pull/595)
```

2023-11-09 19:23 UTC, csarven approved these changes

2023-11-09 19:25 UTC, csarven commented
Thanks all! Will rename to `chair-election` for some clarity after merge.

2023-11-09 19:25 UTC, merged