Add Workspace Selection guidance
w3c-cg/solid pull request #16
Opened 2024-01-22 10:22 UTC by csarven

2024-01-22 11:53 UTC, VirginiaBalseiro approved these changes

2024-01-22 13:28 UTC, michielbdejong approved these changes

2024-01-22 17:14 UTC, TallTed requested changes

2024-01-22 17:14 UTC, TallTed commented on CONTRIBUTING.md
> +and Guidelines, Use Cases and Requirements, Surveys, QA, and so forth.
```suggestion
documents — such as Technical Reports, Primers, Best Practices and Guidelines,
Use Cases and Requirements, Surveys, QA, and so forth — or software.
```

2024-01-22 17:14 UTC, TallTed commented on CONTRIBUTING.md
> +efficiently manage communication and collaboration within the Solid Project.
```suggestion
Consider the following guidance to identify the appropriate workspace to use to
efficiently manage communication and collaboration within the Solid Project.
```

2024-01-22 17:14 UTC, TallTed commented on CONTRIBUTING.md
> +  Item](#new-work-item-proposal)
```suggestion
* involves or spans over various stakeholders, specialized groups, or
  horizontal groupings, then start a Solid Project-wide endeavor
* is about current CG work items, then it should be proposed within or across
  those current work items
* is within the scope of the CG but identifies a gap in work items, then
  follow the procedure to [propose a New Work Item](#new-work-item-proposal)
```

2024-01-22 17:14 UTC, TallTed commented on CONTRIBUTING.md
> +stakeholders, problem context, and technical or knowledge goals.
Should indicate on which repo to create that issue, preferably including a link

2024-01-22 17:34 UTC, csarven commented on CONTRIBUTING.md
> +stakeholders, problem context, and technical or knowledge goals.
```suggestion
If you are unsure where the work may fit, please create an
[issue](https://github.com/solid/specification) detailing the stakeholders,
problem context, and technical or knowledge goals.
```

2024-01-23 12:46 UTC, elf-pavlik approved these changes

2024-02-05 15:40 UTC, merged